In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('Mall_Customers.csv')

In [7]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [9]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [11]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [12]:
grouped= df.groupby('Gender')

In [15]:
stats_summary = grouped.agg(['mean','max','min','std'])
print(stats_summary)

        CustomerID                            Age                     \
              mean  max min        std       mean max min        std
Gender
Female   97.562500  197   3  58.276412  38.098214  68  18  12.644095
Male    104.238636  200   1  57.483830  39.806818  70  18  15.514812

       Annual Income (k$)                     Spending Score (1-100)          \
                     mean  max min        std                   mean max min
Gender
Female          59.250000  126  16  26.011952              51.526786  99   5
Male            62.227273  137  15  26.638373              48.511364  97   1


             std
Gender
Female  24.11495
Male    27.89677

In [17]:
grouped.describe().T

Gender                            Female        Male
CustomerID             count  112.000000   88.000000
                       mean    97.562500  104.238636
                       std     58.276412   57.483830
                       min      3.000000    1.000000
                       25%     46.750000   59.500000
                       50%     94.500000  106.500000
                       75%    148.250000  151.250000
                       max    197.000000  200.000000
Age                    count  112.000000   88.000000
                       mean    38.098214   39.806818
                       std     12.644095   15.514812
                       min     18.000000   18.000000
                       25%     29.000000   27.750000
                       50%     35.000000   37.000000
                       75%     47.500000   50.500000
                       max     68.000000   70.000000
Annual Income (k$)     count  112.000000   88.000000
                       mean    59.250000   62.227273
                       std     26.011952   26.638373
                       min     16.000000   15.000000
                       25%     39.750000   45.500000
                       50%     60.000000   62.500000
                       75%     77.250000   78.000000
                       max    126.000000  137.000000
Spending Score (1-100) count  112.000000   88.000000
                       mean    51.526786   48.511364
                       std     24.114950   27.896770
                       min      5.000000    1.000000
                       25%     35.000000   24.500000
                       50%     50.000000   50.000000
                       75%     73.000000   70.000000
                       max     99.000000   97.000000

In [25]:
bins = [0,20,30,40,50,60,100]
lables =['Teen','Young Adult','Adult','Middle Age','Senior','old']
df['Age_group'] = pd.cut( df['Age'],bins= bins,labels=lables)

In [ ]:
df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Age_group
0,1,Male,19,15,39,Teen
1,2,Male,21,15,81,Young Adult
2,3,Female,20,16,6,Teen
3,4,Female,23,16,77,Young Adult
4,5,Female,31,17,40,Adult

In [31]:
grouped = df.groupby('Age_group')[['Age','Annual Income (k$)','Spending Score (1-100)'	]]
grouped.agg(['mean','std','count','min','max']).T

Age_group                          Teen  Young Adult       Adult  Middle Age  \
Age                    mean   19.058824    25.800000   34.933333   46.605263
                       std     0.747545     3.101319    2.950821    2.726640
                       count  17.000000    45.000000   60.000000   38.000000
                       min    18.000000    21.000000   31.000000   41.000000
                       max    20.000000    30.000000   40.000000   50.000000
Annual Income (k$)     mean   51.117647    56.755556   68.633333   63.605263
                       std    20.563567    28.251432   29.168689   24.152152
                       count  17.000000    45.000000   60.000000   38.000000
                       min    15.000000    15.000000   17.000000   25.000000
                       max    81.000000   137.000000  137.000000  126.000000
Spending Score (1-100) mean   44.647059    67.222222   57.500000   34.394737
                       std    25.211459    19.932715   28.875243   15.931508
                       count  17.000000    45.000000   60.000000   38.000000
                       min     5.000000    12.000000    1.000000    5.000000
                       max    92.000000    97.000000   99.000000   59.000000

Age_group                         Senior        old
Age                    mean    55.869565  66.647059
                       std      3.094046   2.148871
                       count   23.000000  17.000000
                       min     51.000000  63.000000
                       max     60.000000  70.000000
Annual Income (k$)     mean    56.695652  50.000000
                       std     23.026536  14.313455
                       count   23.000000  17.000000
                       min     20.000000  19.000000
                       max    101.000000  65.000000
Spending Score (1-100) mean    32.521739  44.176471
                       std     20.088146  14.858648
                       count   23.000000  17.000000
                       min      4.000000   3.000000
                       max     60.000000  59.000000

In [35]:
df = pd.read_csv('IRIS.csv')

In [36]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [38]:
grouped = df.groupby('species')
stats = grouped.agg(['mean','count','std','min','max'])
print(stats)

                sepal_length                           sepal_width        \
                        mean count       std  min  max        mean count
species
Iris-setosa            5.006    50  0.352490  4.3  5.8       3.418    50
Iris-versicolor        5.936    50  0.516171  4.9  7.0       2.770    50
Iris-virginica         6.588    50  0.635880  4.9  7.9       2.974    50

                                    petal_length                            \
                      std  min  max         mean count       std  min  max
species
Iris-setosa      0.381024  2.3  4.4        1.464    50  0.173511  1.0  1.9
Iris-versicolor  0.313798  2.0  3.4        4.260    50  0.469911  3.0  5.1
Iris-virginica   0.322497  2.2  3.8        5.552    50  0.551895  4.5  6.9

                petal_width
                       mean count       std  min  max
species
Iris-setosa           0.244    50  0.107210  0.1  0.6
Iris-versicolor       1.326    50  0.197753  1.0  1.8
Iris-virginica        2.026    50  0.274650  1.4  2.5

In [40]:
grouped.describe().T

species             Iris-setosa  Iris-versicolor  Iris-virginica
sepal_length count    50.000000        50.000000       50.000000
             mean      5.006000         5.936000        6.588000
             std       0.352490         0.516171        0.635880
             min       4.300000         4.900000        4.900000
             25%       4.800000         5.600000        6.225000
             50%       5.000000         5.900000        6.500000
             75%       5.200000         6.300000        6.900000
             max       5.800000         7.000000        7.900000
sepal_width  count    50.000000        50.000000       50.000000
             mean      3.418000         2.770000        2.974000
             std       0.381024         0.313798        0.322497
             min       2.300000         2.000000        2.200000
             25%       3.125000         2.525000        2.800000
             50%       3.400000         2.800000        3.000000
             75%       3.675000         3.000000        3.175000
             max       4.400000         3.400000        3.800000
petal_length count    50.000000        50.000000       50.000000
             mean      1.464000         4.260000        5.552000
             std       0.173511         0.469911        0.551895
             min       1.000000         3.000000        4.500000
             25%       1.400000         4.000000        5.100000
             50%       1.500000         4.350000        5.550000
             75%       1.575000         4.600000        5.875000
             max       1.900000         5.100000        6.900000
petal_width  count    50.000000        50.000000       50.000000
             mean      0.244000         1.326000        2.026000
             std       0.107210         0.197753        0.274650
             min       0.100000         1.000000        1.400000
             25%       0.200000         1.200000        1.800000
             50%       0.200000         1.300000        2.000000
             75%       0.300000         1.500000        2.300000
             max       0.600000         1.800000        2.500000